name: ECS Deployment
on:
  push:
    branches:
      - main
    # paths-ignore:
    # - '.github/workflows/*' #워크플로우가 수정되면 액션이 실행안됨

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.test.outputs.status }} #outputs는 Job의 결과를 외부로 전달하기 위해 사용되며, Step 간에는 단순히 ${{ steps.<step_id>.<value> }} 형식으로 값을 공유할 수 있습니다.
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: /home/runner/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          pnpm install
          echo "PNPM cache path:"
          pnpm store path

      - name: Run tests
        id: test
        run: |
          pnpm test

        # continue-on-error: true

      - name: Check test status
        if: failure() && steps.test.outcome == 'failure'
        run: |
          echo "Step conclusion: ${{ steps.test.conclusion }}"
          echo "Step outcome: ${{ steps.test.outcome }}"

      - name: Upload test logs on failure
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-logs #다운로드가능한 아티팩트 이름
          path: test

  deploy:
    needs: test
    env:
      URL: asdasd
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: /home/runner/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install
