name: ECS Deployment
on:
  push:
    branches:
      - main
    # paths-ignore:
    # - '.github/workflows/*' #워크플로우가 수정되면 액션이 실행안됨

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Check PNPM installation path
      - name: Debug PNPM installation path
        run: |
          echo "PNPM version:"
          pnpm --version
          echo "PNPM installation path:"
          which pnpm

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store #지정된 디렉토리를 캐시합니다.
          key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      # - name: Run tests
      #   run: |
      #     pnpm test
      #   continue-on-error: true
      # outputs:
      # status: ${{ steps.test.outputs.status }}

      - name: Upload test logs on failure
        # if: failure() # 이전 단계에서 실패했을 경우에만 실행
        uses: actions/upload-artifact@v4
        with:
          name: test-logs #다운로드가능한 아티팩트 이름
          path: dist

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store #지정된 디렉토리를 캐시합니다.
          key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install
